### ISSUE TITLE
Add llvm tests

### ISSUE THREAD

**Issue by jrmuizel** [mstange/msvc-demangler-rust#39]
llvm now has an msvc demangler https://github.com/llvm-mirror/llvm/blob/master/lib/Demangle/MicrosoftDemangle.cpp

We should make sure we pass their tests:
https://github.com/llvm-mirror/llvm/tree/master/test/Demangle

**Comment by mitsuhiko** [comment]
I started pulling these in in #42

**Comment by mitsuhiko** [comment]
I'm closing this now. The tests are there but they are not all enabled yet (I only activated two so far) because they need reviewing and lots of adjustments. I think we should open individual issues as we enable more.
