### ISSUE TITLE
Implement read_nested_name()

### ISSUE THREAD

**Issue by jrmuizel** [mstange/msvc-demangler-rust#6]
Currently read_name() looks like:
 ```read_unqualified_name() (read_unqualified_name())* @```
it should be
```read_unqualified_name() (read_nested_name())* @```

read_nested_name() has different semantics than read_unqualified_name().

I have the beginnings of a patch to do this.

**Comment by mstange** [comment]
You implemented this in 4d1e23162482d8cd3467eb7f7c475e61a712e9a9.
