### ISSUE TITLE
The storage class for variables is ignored

### ISSUE THREAD

**Issue by jrmuizel** [mstange/msvc-demangler-rust#7]
read_var_type currently takes StoreClass::empty() as param, but the storage class comes after the type in the mangled symbol

**Comment by mitsuhiko** [comment]
I have a fix for this in #42. I'm not sure the approach is correct but this is modeled after how LLVM represents this.

**Comment by mitsuhiko** [comment]
I'm closing this now. It's not ignored any more but we might have to revisit this design decision.
